version: '3'
services:
    web:
        container_name: app
        build: ./app
        ports:
            - "5000:5000"
        volumes:
            - ./app:/app
        depends_on:
            - redis-container

    redis-container:
        container_name: redis
        image: redis

